export const CONTROLLERS_INFO = {
  AUTH: { TAG: 'Auth', DESCRIPTION: 'Admin login, session and passkeys (session-only)' },
  API_TOKENS: { TAG: 'API Tokens', DESCRIPTION: 'Create and revoke API tokens (session-only)' },
  ACCOUNTS: { TAG: 'Accounts', DESCRIPTION: 'Member accounts with scoped access' },
  PROVIDERS: { TAG: 'Providers', DESCRIPTION: 'Hosting provider accounts' },
  PROJECTS: { TAG: 'Projects', DESCRIPTION: 'Group services by project' },
  SYNC: { TAG: 'Sync', DESCRIPTION: 'Trigger and inspect provider syncs' },
  SERVICES: { TAG: 'Services', DESCRIPTION: 'Paid resources at providers' },
  PAYMENTS: { TAG: 'Payments', DESCRIPTION: 'Log of actual payments' },
  ANALYTICS: { TAG: 'Analytics', DESCRIPTION: 'Spend summary and forecast' },
  BALANCE_HISTORY: { TAG: 'Balance History', DESCRIPTION: 'Provider balance snapshots' },
  RATES: { TAG: 'Exchange Rates', DESCRIPTION: 'Currency rates to the base currency' },
  SETTINGS: { TAG: 'Settings', DESCRIPTION: 'Panel settings' },
  NOTIFICATIONS: { TAG: 'Notifications', DESCRIPTION: 'Outgoing Telegram notifications' },
  HEALTH: { TAG: 'Health', DESCRIPTION: 'Liveness check' },
  BUILD_INFO: { TAG: 'Build Info', DESCRIPTION: 'Build metadata' },
} as const;
